### ISSUE TITLE
Output file headers are inconsistent

### ISSUE THREAD

**Issue by chadtilbury** [csababarta/memory-baseliner#1]
When no additional options are chosen, each file output has a first line of PROCESSES | SERVICES | DRIVERS, but these are not present when other options are chosen (which is the likely desired state).  I would vote to remove them altogether as they make it more difficult to filter data in tools like Excel/Timeline Explorer.  I recommend having the first line be the column names for all output types for easy import into other tools.

**Comment by csababarta** [comment]
Pushed a version that should fix this issue
